### PR TITLE
trying to capture the response from some endpoints

### PR DESCRIPTION
**Pull request by nei**
Work in progress, I can see the requests going through but cant get the response.

### CODE REVIEW

**Comment by GLabat** [comment]
Hi

Not sure if you saw my comment on the Slack channel.

Some ideas:
• make sure that the `response.request().url()` really ends with “customer-info”. Maybe try a ‘match’ instead of `endsWith`
• are you sure that the response is a text response? If it is a JSON, you should use `response.json().then…`
• `const responses = new Map();`. Since `responses` is a Map, you should use `//responses.set(response.request().url(), textBody);` instead of `//responses[response.request().url()] = textBody;`

Hope this helps

**Comment by nei** [comment]
Hi @GLabat thank you for your help.. I've tried this:

```
const responses = new Map();
	page.on('response', response => {

		if ('xhr' !== response.request().resourceType()){
            return ;
		}

		response.json().then(function (json){
			responses.set(response.request().url(), json)
		});

		console.log(responses.keys())
	});
```

I can see the urls all the urls that returned json.. but the ulrs I am interested is not on the list.

```
MapIterator {
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919' }
MapIterator {
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919' }
MapIterator {
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919',
  'https://faq.directtalk.com.br/1.0/api//Configuration/GetFormsUrl',
  'https://faq.directtalk.com.br/1.0/api/appearance/6535fe86-be4f-4424-bb05-97e6c07638b0' }
MapIterator {
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919',
  'https://faq.directtalk.com.br/1.0/api//Configuration/GetFormsUrl',
  'https://faq.directtalk.com.br/1.0/api/appearance/6535fe86-be4f-4424-bb05-97e6c07638b0',
  'https://faq.directtalk.com.br/1.0/api/integration/interface/a38f1c3b-bb14-43a9-9f56-de3bb77b7130' }
MapIterator {
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919',
  'https://faq.directtalk.com.br/1.0/api//Configuration/GetFormsUrl',
  'https://faq.directtalk.com.br/1.0/api/appearance/6535fe86-be4f-4424-bb05-97e6c07638b0',
  'https://faq.directtalk.com.br/1.0/api/integration/interface/a38f1c3b-bb14-43a9-9f56-de3bb77b7130',
  'https://targeting-version-voxusmidia.netdna-ssl.com/v/' }
(node:97676) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token g in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (/Users/nei/Projects/rico-puppeteer/node_modules/puppeteer/lib/NetworkManager.js:626:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:97676) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:97676) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
MapIterator {
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919',
  'https://faq.directtalk.com.br/1.0/api//Configuration/GetFormsUrl',
  'https://faq.directtalk.com.br/1.0/api/appearance/6535fe86-be4f-4424-bb05-97e6c07638b0',
  'https://faq.directtalk.com.br/1.0/api/integration/interface/a38f1c3b-bb14-43a9-9f56-de3bb77b7130',
  'https://targeting-version-voxusmidia.netdna-ssl.com/v/' }
MapIterator {
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919',
  'https://faq.directtalk.com.br/1.0/api//Configuration/GetFormsUrl',
  'https://faq.directtalk.com.br/1.0/api/appearance/6535fe86-be4f-4424-bb05-97e6c07638b0',
  'https://faq.directtalk.com.br/1.0/api/integration/interface/a38f1c3b-bb14-43a9-9f56-de3bb77b7130',
  'https://targeting-version-voxusmidia.netdna-ssl.com/v/',
  'https://api.voxus.tv/verify/?adv_id=96&ck_id=&ipa=true' }
MapIterator {
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919',
  'https://faq.directtalk.com.br/1.0/api//Configuration/GetFormsUrl',
  'https://faq.directtalk.com.br/1.0/api/appearance/6535fe86-be4f-4424-bb05-97e6c07638b0',
  'https://faq.directtalk.com.br/1.0/api/integration/interface/a38f1c3b-bb14-43a9-9f56-de3bb77b7130',
  'https://targeting-version-voxusmidia.netdna-ssl.com/v/',
  'https://api.voxus.tv/verify/?adv_id=96&ck_id=&ipa=true',
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919&utk=1d3f2cc280edc35eb56a74b2872534a2' }
MapIterator {
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919',
  'https://faq.directtalk.com.br/1.0/api//Configuration/GetFormsUrl',
  'https://faq.directtalk.com.br/1.0/api/appearance/6535fe86-be4f-4424-bb05-97e6c07638b0',
  'https://faq.directtalk.com.br/1.0/api/integration/interface/a38f1c3b-bb14-43a9-9f56-de3bb77b7130',
  'https://targeting-version-voxusmidia.netdna-ssl.com/v/',
  'https://api.voxus.tv/verify/?adv_id=96&ck_id=&ipa=true',
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919&utk=1d3f2cc280edc35eb56a74b2872534a2' }
(node:97676) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token g in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (/Users/nei/Projects/rico-puppeteer/node_modules/puppeteer/lib/NetworkManager.js:626:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:97676) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
MapIterator {
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919',
  'https://faq.directtalk.com.br/1.0/api//Configuration/GetFormsUrl',
  'https://faq.directtalk.com.br/1.0/api/appearance/6535fe86-be4f-4424-bb05-97e6c07638b0',
  'https://faq.directtalk.com.br/1.0/api/integration/interface/a38f1c3b-bb14-43a9-9f56-de3bb77b7130',
  'https://targeting-version-voxusmidia.netdna-ssl.com/v/',
  'https://api.voxus.tv/verify/?adv_id=96&ck_id=&ipa=true',
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919&utk=1d3f2cc280edc35eb56a74b2872534a2' }
MapIterator {
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919',
  'https://faq.directtalk.com.br/1.0/api//Configuration/GetFormsUrl',
  'https://faq.directtalk.com.br/1.0/api/appearance/6535fe86-be4f-4424-bb05-97e6c07638b0',
  'https://faq.directtalk.com.br/1.0/api/integration/interface/a38f1c3b-bb14-43a9-9f56-de3bb77b7130',
  'https://targeting-version-voxusmidia.netdna-ssl.com/v/',
  'https://api.voxus.tv/verify/?adv_id=96&ck_id=&ipa=true',
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919&utk=1d3f2cc280edc35eb56a74b2872534a2' }
MapIterator {
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919',
  'https://faq.directtalk.com.br/1.0/api//Configuration/GetFormsUrl',
  'https://faq.directtalk.com.br/1.0/api/appearance/6535fe86-be4f-4424-bb05-97e6c07638b0',
  'https://faq.directtalk.com.br/1.0/api/integration/interface/a38f1c3b-bb14-43a9-9f56-de3bb77b7130',
  'https://targeting-version-voxusmidia.netdna-ssl.com/v/',
  'https://api.voxus.tv/verify/?adv_id=96&ck_id=&ipa=true',
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919&utk=1d3f2cc280edc35eb56a74b2872534a2' }
MapIterator {
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919',
  'https://faq.directtalk.com.br/1.0/api//Configuration/GetFormsUrl',
  'https://faq.directtalk.com.br/1.0/api/appearance/6535fe86-be4f-4424-bb05-97e6c07638b0',
  'https://faq.directtalk.com.br/1.0/api/integration/interface/a38f1c3b-bb14-43a9-9f56-de3bb77b7130',
  'https://targeting-version-voxusmidia.netdna-ssl.com/v/',
  'https://api.voxus.tv/verify/?adv_id=96&ck_id=&ipa=true',
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919&utk=1d3f2cc280edc35eb56a74b2872534a2' }
MapIterator {
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919',
  'https://faq.directtalk.com.br/1.0/api//Configuration/GetFormsUrl',
  'https://faq.directtalk.com.br/1.0/api/appearance/6535fe86-be4f-4424-bb05-97e6c07638b0',
  'https://faq.directtalk.com.br/1.0/api/integration/interface/a38f1c3b-bb14-43a9-9f56-de3bb77b7130',
  'https://targeting-version-voxusmidia.netdna-ssl.com/v/',
  'https://api.voxus.tv/verify/?adv_id=96&ck_id=&ipa=true',
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919&utk=1d3f2cc280edc35eb56a74b2872534a2' }
(node:97676) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (/Users/nei/Projects/rico-puppeteer/node_modules/puppeteer/lib/NetworkManager.js:626:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:97676) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
MapIterator {
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919',
  'https://faq.directtalk.com.br/1.0/api//Configuration/GetFormsUrl',
  'https://faq.directtalk.com.br/1.0/api/appearance/6535fe86-be4f-4424-bb05-97e6c07638b0',
  'https://faq.directtalk.com.br/1.0/api/integration/interface/a38f1c3b-bb14-43a9-9f56-de3bb77b7130',
  'https://targeting-version-voxusmidia.netdna-ssl.com/v/',
  'https://api.voxus.tv/verify/?adv_id=96&ck_id=&ipa=true',
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919&utk=1d3f2cc280edc35eb56a74b2872534a2',
  'https://dtbot.directtalk.com.br/1.0/api//Configuration/GetFormsUrl',
  'https://dtbot.directtalk.com.br/1.0/api/Configuration/Department/651ad38a-4b35-4322-9d3b-86152dc4a0d0/config',
  'https://dtbot.directtalk.com.br/1.0/api/Configuration/Department/651ad38a-4b35-4322-9d3b-86152dc4a0d0/advanced',
  'https://dtbot.directtalk.com.br/1.0/api/Configuration/Department/651ad38a-4b35-4322-9d3b-86152dc4a0d0/satisfactionFormId' }
MapIterator {
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919',
  'https://faq.directtalk.com.br/1.0/api//Configuration/GetFormsUrl',
  'https://faq.directtalk.com.br/1.0/api/appearance/6535fe86-be4f-4424-bb05-97e6c07638b0',
  'https://faq.directtalk.com.br/1.0/api/integration/interface/a38f1c3b-bb14-43a9-9f56-de3bb77b7130',
  'https://targeting-version-voxusmidia.netdna-ssl.com/v/',
  'https://api.voxus.tv/verify/?adv_id=96&ck_id=&ipa=true',
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919&utk=1d3f2cc280edc35eb56a74b2872534a2',
  'https://dtbot.directtalk.com.br/1.0/api//Configuration/GetFormsUrl',
  'https://dtbot.directtalk.com.br/1.0/api/Configuration/Department/651ad38a-4b35-4322-9d3b-86152dc4a0d0/config',
  'https://dtbot.directtalk.com.br/1.0/api/Configuration/Department/651ad38a-4b35-4322-9d3b-86152dc4a0d0/advanced',
  'https://dtbot.directtalk.com.br/1.0/api/Configuration/Department/651ad38a-4b35-4322-9d3b-86152dc4a0d0/satisfactionFormId',
  'https://dtbot.directtalk.com.br/1.0/api/integration/interface/651ad38a-4b35-4322-9d3b-86152dc4a0d0' }
(node:97676) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (/Users/nei/Projects/rico-puppeteer/node_modules/puppeteer/lib/NetworkManager.js:626:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:97676) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
MapIterator {
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919',
  'https://faq.directtalk.com.br/1.0/api//Configuration/GetFormsUrl',
  'https://faq.directtalk.com.br/1.0/api/appearance/6535fe86-be4f-4424-bb05-97e6c07638b0',
  'https://faq.directtalk.com.br/1.0/api/integration/interface/a38f1c3b-bb14-43a9-9f56-de3bb77b7130',
  'https://targeting-version-voxusmidia.netdna-ssl.com/v/',
  'https://api.voxus.tv/verify/?adv_id=96&ck_id=&ipa=true',
  'https://forms.hubspot.com/lead-flows-config/v1/config/json?portalId=292919&utk=1d3f2cc280edc35eb56a74b2872534a2',
  'https://dtbot.directtalk.com.br/1.0/api//Configuration/GetFormsUrl',
  'https://dtbot.directtalk.com.br/1.0/api/Configuration/Department/651ad38a-4b35-4322-9d3b-86152dc4a0d0/config',
  'https://dtbot.directtalk.com.br/1.0/api/Configuration/Department/651ad38a-4b35-4322-9d3b-86152dc4a0d0/advanced',
  'https://dtbot.directtalk.com.br/1.0/api/Configuration/Department/651ad38a-4b35-4322-9d3b-86152dc4a0d0/satisfactionFormId',
  'https://dtbot.directtalk.com.br/1.0/api/integration/interface/651ad38a-4b35-4322-9d3b-86152dc4a0d0' }
```
For some reason not all responses are being captured.

**Comment by GLabat** [comment]
Hi

I manage to get the response to the call to 'customer-info' with the following code. I'm not logged in so the response is empty (with Puppeteer 1.6.0).
I added a wait option to `goto` so that the page remains loading until pending requests are done.

```js
const puppeteer = require('puppeteer')

puppeteer.launch().then(async browser => {
  const page = await browser.newPage()

  await page.setViewport({ width: 1440, height: 900, deviceScaleFactor: 2 })

  page.on('response', response => {
    const resourceType = response.request().resourceType()
    const resourceURL = response.request().url()
    if ('xhr' !== resourceType) {
      return
    }
    if (resourceURL.endsWith('customer-info')) {
      response.json().then(json => {
        console.log(json) // eslint-disable-line
      })
    }
  })
  await page.goto('https://www.rico.com.vc', {
    waitUntil: 'networkidle0'
  })

  await browser.close()
})

```

**Comment by nei** [comment]
Thank @GLabat 

I've tried this yesterday but forgot to commit. Something else is wrong, puppeteer seems not to be handling these events properly.

I've counted the number of events happening and it does not seem to match.
```
request: 484
requestfinished: 146
requestfailed: 69
response: 155
````

**Comment by nei** [comment]
Require this change to actually import the ajax calls https://github.com/GoogleChrome/puppeteer/pull/2954

**Comment by GLabat** [comment]
Hi

I took some days off ;-)

Good to know you manage to find out the issue.
Seems to be fixed in Puppeteer 1.7 => https://github.com/GoogleChrome/puppeteer/releases/tag/v1.7.0 (#2970)

**Comment by nei** [comment]
nice one, tks @GLabat  appreciate your help.

**Pull request merged**
